version: "3.8"

services:
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Root123456"
      MSSQL_PID: "Express"
      MSSQL_DATABASE: "GymMembershipDb"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sh:/init-db.sh
    command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Root123456 -C -Q 'IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N''GymMembershipDb'') CREATE DATABASE GymMembershipDb' && wait"
    restart: unless-stopped

volumes:
  sqlserver_data:
